# Generated by Django 4.2 on 2024-08-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('name_en', models.CharField(max_length=128, null=True, unique=True)),
                ('name_tet', models.CharField(max_length=128, null=True, unique=True)),
            ],
        ),
    ]
