# Generated by Django 4.2 on 2024-07-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suco_obulo', '0002_post_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name_en',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_tet',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='overview_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='overview_tet',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_tet',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
