# Generated by Django 4.2 on 2026-04-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suco_obulo', '0002_obulo_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='description_tet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='obulo_images/'),
        ),
    ]
